name:                profunctor-hep
version:             0.1.0.0
github:              "cspollard/profunctor-hep"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com"
copyright:           "2019 Chris Pollard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cspollard/profunctor-hep#readme>

default-extensions:
- RankNTypes
- GADTs
- TypeOperators
- TypeFamilies
- TupleSections
- ScopedTypeVariables
- TypeApplications

dependencies:
- base >= 4.7 && < 5
- lens
- profunctors
- primitive
- bifunctors
- extensible
- monoidal-containers
- hashable
- deriving-compat
- functor-combinators
- deriving-compat
- vector
- foldl
- free
- kan-extensions

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  profunctor-hep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - profunctor-hep
